name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker for Minikube on Windows
      shell: pwsh
      run: |
        $envVars = & minikube -p minikube docker-env --shell powershell
        $envText = $envVars -join "`n"
        Invoke-Expression $envText

    - name: Build Frontend Image
      run: docker build -t umer515k/frontend:latest ./frontend

    - name: Build Backend Image
      run: docker build -t umer515k/backend:latest ./backend

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Images
      run: |
        docker push umer515k/frontend:latest
        docker push umer515k/backend:latest

    - name: Create Namespace if not exists
      run: |
        kubectl get namespace mern-app || kubectl create namespace mern-app
        
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/mongodb/ -n mern-app
        kubectl apply -f k8s/backend/ -n mern-app
        kubectl apply -f k8s/frontend/ -n mern-app
        kubectl rollout restart deployment frontend -n mern-app
        kubectl rollout restart deployment backend -n mern-app
